#!/bin/bash

########################################################################
# CDTux: lightweigth Ubuntu/Raspbian « distribution »
#
# Copyright (C) 2017 Christophe Delord
# http://www.cdsoft.fr/cdtux
#
# This file is part of CDTux
#
# PI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CDTux is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CDTux  If not, see <http://www.gnu.org/licenses/>.
########################################################################

cd $(dirname $0)
. scripts/config

title "CDTux configuration script"
info "See http://cdsoft.fr/cdtux for further information"

case "$1" in
    edit|config)
        vi $CDTUXRC
        ;;
    *)
        export PATH=$(echo $PATH | sed -e 's/^.://' -e 's/:.$//' -e 's/:.:/:/')
        find scripts -type f -executable -execdir ./$(basename {}) \;
        ;;
esac
