#!/bin/bash

. ./config
$INTEL || exit

title "Atom"

INSTALL_FROM_REPOSITORY=false

if $INSTALL_FROM_REPOSITORY
then

    sudo apt install atom

else

    # http://stackoverflow.com/questions/3074288/get-url-after-redirect
    URL=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/atom/atom/releases/latest)

    TAG=$(basename $URL)
    ATOMDEB=https://github.com/atom/atom/releases/download/$TAG/atom-amd64.deb

    get $ATOMDEB
    sudo dpkg -E -i $CACHE/$(basename $ATOMDEB)

fi
