#!/bin/bash

. ./config

title "Elixir"

ERLANG=https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
get $ERLANG
sudo dpkg -E -i $CACHE/$(basename $ERLANG)
sudo apt update
#sudo apt install esl-erlang
sudo apt install elixir
